# Personalize your website info here
title:            Bin Li
tagline:          'Professional Website for Bin Li'
description:      'Website and Blog for Bin Li'
url:              http://libin99nju.github.io
author:
  name:           'Bin Li'
  url:            https://twitter.com/anewguy

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
