# Personalize your website info here
title:            Bin Li
tagline:
description:      'Hello World!'
url:              http://libin99nju.github.io
author:           Bin
name:
url:            https://twitter.com/libin99nju

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
